version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0
jobs:
  build_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: pnpm install
      - run:
          command: pnpm build
          name: Build app
      - run: ls ./dist
      - aws-cli/setup:
          role_arn: arn:aws:iam::743637611281:role/circle-ci-role
          role_session_name: setup
      - aws-s3/sync:
          from: ./dist
          to: s3://lightnoweat.com

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_deploy
